// Utils functions editor

/**
 * 
 * @param fileNamePath Contenting string filename and full path
 * @returns File extension Ex: 'txt', 'js', 'php'...
 */
export const fileNamePathToExtension = (fileNamePath: string | null): string => {
    if (!fileNamePath) return 'text';
  
  const extension = fileNamePath.split('.').pop()?.toLowerCase();

  switch (extension) {
    // Arquivos comuns
    case 'html':
    case 'htm':
      return 'html';
    case 'css':
      return 'css';
    case 'json':
      return 'json';
    case 'js':
    case 'mjs':
    case 'cjs':
      return 'javascript';
    case 'jsx':
      return 'jsx';
    case 'ts':
    case 'typescript':
      return 'typescript';
    case 'tsx':
      return 'tsx';
    case 'php':
    case 'php3':
    case 'php4':
    case 'php5':
    case 'phtml':
      return 'php';
    case 'py':
    case 'pyw':
      return 'python';

    // Adições
    case 'abap':
      return 'abap';
    case 'abc':
      return 'abc';
    case 'as':
    case 'actionscript':
      return 'actionscript';
    case 'ada':
    case 'adb':
    case 'ads':
      return 'ada';
    case 'alda':
      return 'alda';
    case 'apache_conf':
    case 'conf':           
      return 'apache_conf';
    case 'apex':
      return 'apex';
    case 'applescript':
    case 'scpt':
      return 'applescript';
    case 'aql':
      return 'aql';
    case 'asciidoc':
    case 'adoc':
      return 'asciidoc';
    case 'asl':
      return 'asl';
    case 's':
    case 'asm':
    case 'arm':
      return 'assembly_arm32';
    case 'asm_x86':
      return 'assembly_x86';
    case 'astro':
      return 'astro';
    case 'ahk':
    case 'autohotkey':
      return 'autohotkey';
    case 'bas':
    case 'basic':
      return 'basic';
    case 'bat':
    case 'cmd':
      return 'batchfile';
    case 'bib':
    case 'bibtex':
      return 'bibtex';
    case 'c9search':
      return 'c9search';
    case 'c':
    case 'cpp':
    case 'cxx':
    case 'h':
    case 'hpp':
      return 'c_cpp';
    case 'cedar':
      return 'cedar';
    case 'cedarschema':
      return 'cedarschema';
    case 'cirru':
      return 'cirru';
    case 'clj':
    case 'cljs':
    case 'cljc':
      return 'clojure';
    case 'clue':
      return 'clue';
    case 'cob':
    case 'cobol':
      return 'cobol';
    case 'coffee':
    case 'cson':
    case 'iced':
      return 'coffee';
    case 'cfm':
    case 'cfml':
      return 'coldfusion';
    case 'cr':
      return 'crystal';
    case 'cs':
      return 'csharp';
    case 'csd':
      return 'csound_document';
    case 'orc':
      return 'csound_orchestra';
    case 'sco':
      return 'csound_score';
    case 'csp':
      return 'csp';
    case 'csv':
      return 'csv';
    case 'curly':
      return 'curly';
    case 'cuttlefish':
      return 'cuttlefish';
    case 'd':
      return 'd';
    case 'dart':
      return 'dart';
    case 'diff':
    case 'patch':
      return 'diff';
    case 'django':
    case 'jinja':
      return 'django';
    case 'dockerfile':
    case 'docker':
      return 'dockerfile';
    case 'dot':
      return 'dot';
    case 'drl':
      return 'drools';
    case 'edi':
    case 'edifact':
      return 'edifact';
    case 'e':
    case 'eiffel':
      return 'eiffel';
    case 'ejs':
      return 'ejs';
    case 'ex':
    case 'exs':
      return 'elixir';
    case 'elm':
      return 'elm';
    case 'erl':
    case 'hrl':
      return 'erlang';
    case 'flix':
      return 'flix';
    case 'fth':
    case '4th':
    case 'forth':
      return 'forth';
    case 'f':
    case 'for':
    case 'f77':
    case 'f90':
      return 'fortran';
    case 'fs':
    case 'fsi':
    case 'fsx':
      return 'fsharp';
    case 'fsl':
      return 'fsl';
    case 'ftl':
      return 'ftl';
    case 'gcode':
    case 'nc':
      return 'gcode';
    case 'feature':
      return 'gherkin';
    case 'gitignore':
      return 'gitignore';
    case 'glsl':
    case 'vert':
    case 'frag':
      return 'glsl';
    case 'gobstones':
      return 'gobstones';
    case 'go':
      return 'golang';
    case 'graphql':
    case 'gql':
      return 'graphqlschema';
    case 'groovy':
    case 'gvy':
      return 'groovy';
    case 'groq':
      return 'groq';
    case 'haml':
      return 'haml';
    case 'hbs':
    case 'handlebars':
      return 'handlebars';
    case 'hs':
    case 'lhs':
      return 'haskell';
    case 'cabal':
      return 'haskell_cabal';
    case 'hx':
    case 'hxml':
      return 'haxe';
    case 'hjson':
      return 'hjson';
    case 'html_eex':
      return 'html_elixir';
    case 'html_erb':
      return 'html_ruby';
    case 'ini':
    case 'cfg':
      return 'ini';
    case 'io':
      return 'io';
    case 'ion':
      return 'ion';
    case 'jack':
      return 'jack';
    case 'jade':
    case 'pug':
      return 'jade';
    case 'java':
    case 'jav':
      return 'java';
    case 'jexl':
      return 'jexl';
    case 'json5':
      return 'json5';
    case 'jq':
      return 'jsoniq';
    case 'jsp':
      return 'jsp';
    case 'jssm':
      return 'jssm';
    case 'jl':
      return 'julia';
    case 'kt':
    case 'kts':
      return 'kotlin';
    case 'tex':            
    case 'latex':
    case 'ltx':
      return 'latex';
    case 'latte':
      return 'latte';
    case 'less':
      return 'less';
    case 'liquid':
      return 'liquid';
    case 'lisp':
    case 'lsp':
    case 'el':
      return 'lisp';
    case 'ls':
      return 'livescript';
    case 'logic':
      return 'logiql';
    case 'logtalk':
      return 'logtalk';
    case 'lsl':
      return 'lsl';
    case 'lua':
      return 'lua';
    case 'lp':
      return 'luapage';
    case 'lucene':
      return 'lucene';
    case 'makefile':
    case 'mk':
    case 'mak':
      return 'makefile';
    case 'mariadb':
      return 'mariadb';
    case 'md':
    case 'markdown':
    case 'mdown':
    case 'mkd':
      return 'markdown';
    case 'mask':
      return 'mask';
    case 'matlab':
    case 'm':              
      return 'matlab';
    case 'maze':
      return 'maze';
    case 'mediawiki':
    case 'wiki':
      return 'mediawiki';
    case 'mel':
      return 'mel';
    case 'mips':
      return 'mips';
    case 'mixal':
      return 'mixal';
    case 'mush':
      return 'mushcode';
    case 'mysql':
      return 'mysql';
    case 'nginx':          
      return 'nginx';
    case 'nim':
      return 'nim';
    case 'nix':
      return 'nix';
    case 'nsi':
    case 'nsh':
      return 'nsis';
    case 'njk':
    case 'nunjucks':
      return 'nunjucks';
    case 'mm':             
    case 'M':
      return 'objectivec';
    case 'ml':
    case 'mli':
      return 'ocaml';
    case 'pas':
    case 'pascal':
      return 'pascal';
    case 'pl':
    case 'pm':
    case 't':
      return 'perl';
    case 'pgsql':
      return 'pgsql';
    case 'blade.php':
      return 'php_laravel_blade';
    case 'pig':
      return 'pig';
    case 'txt':    
      return 'text';
    case 'ps1':
    case 'psm1':
    case 'psd1':
      return 'powershell';
    case 'praat':
      return 'praat';
    case 'prisma':
      return 'prisma';
    case 'pro':
    case 'prolog':
      return 'prolog';
    case 'properties':
      return 'properties';
    case 'proto':
      return 'protobuf';
    case 'pp':
      return 'puppet';
    case 'qml':
      return 'qml';
    case 'r':
    case 'R':
      return 'r';
    case 'razor':
    case 'cshtml':
      return 'razor';
    case 'rd':
    case 'rdoc':
      return 'rdoc';
    case 'red':
      return 'red';
    case 'redshift':
      return 'redshift';
    case 'rhtml':
      return 'rhtml';
    case 'riscv':
      return 'riscv';
    case 'robot':
      return 'robot';
    case 'rb':
    case 'gemspec':
    case 'rake':
      return 'ruby';
    case 'rs':
      return 'rust';
    case 'sac':
      return 'sac';
    case 'sass':
      return 'sass';
    case 'scad':
      return 'scad';
    case 'scala':
      return 'scala';
    case 'scm':
    case 'ss':
      return 'scheme';
    case 'scss':
      return 'scss';
    case 'sh':
    case 'bash':
    case 'zsh':
    case 'ksh':
      return 'sh';
    case 'sjs':
      return 'sjs';
    case 'slim':
      return 'slim';
    case 'tpl':
      return 'smarty';
    case 'snippets':
      return 'snippets';
    case 'soy':
      return 'soy_template';
    case 'space':
      return 'space';
    case 'rq':
    case 'sparql':
      return 'sparql';
    case 'sql':
      return 'sql';
    case 'sqlserver':
      return 'sqlserver';
    case 'styl':
      return 'stylus';
    case 'svg':
      return 'svg';
    case 'swift':
      return 'swift';
    case 'tcl':
      return 'tcl';
    case 'tf':
    case 'tfvars':
      return 'terraform';    
    case 'textile':
      return 'textile';
    case 'toml':
      return 'toml';
    case 'ttl':
      return 'turtle';
    case 'twig':
      return 'twig';
    case 'vala':
      return 'vala';
    case 'vb':
    case 'vbs':
      return 'vb';
    case 'vm':
    case 'vtl':
      return 'velocity';
    case 'v':
    case 'vh':
    case 'sv':
      return 'verilog';
    case 'vhd':
    case 'vhdl':
      return 'vhdl';
    case 'page':
      return 'visualforce';
    case 'wollok':
      return 'wollok';
    case 'xml':
    case 'xsd':
    case 'xsl':
    case 'wsdl':
      return 'xml';
    case 'xq':
    case 'xquery':
      return 'xquery';
    case 'yml':
    case 'yaml':
      return 'yaml';
    case 'zeek':
      return 'zeek';
    default:
      return 'text'; // Fallback seguro para arquivos de texto genéricos (.txt, .log, etc.)
  }
}